# Generated by Django 5.0 on 2023-12-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='productos_table',
        ),
    ]
